### PR TITLE
feat: add cluster data retrieval and enhance ID mapping functionality

### PR DESCRIPTION
**Pull request by alexlovelltroy**

### CODE REVIEW

**Comment by davidallendj** [comment]
What's the expected output for this PR? Should I see instance data defined in https://github.com/OpenCHAMI/cloud-init/issues/34 whenever I make a request to cloud-init?

**Comment by alexlovelltroy** [comment]
No.  The instance-data is at it's own url

https://github.com/OpenCHAMI/cloud-init/blob/f7e6acd9b04daf2eee5129ef8ddc43e67907b4b8/cmd/cloud-init-server/main.go#L121

**Comment by davidallendj** [comment]
I'm getting a panic when I try to make a request to the endpoint with `curl -k $CLOUD_INIT_URL/instance-data`:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
 
 -> github.com/OpenCHAMI/cloud-init/internal/smdclient.(*SMDClient).getSMD
 ->   /opt/shared/cloud-init/internal/smdclient/SMDclient.go:115

    github.com/OpenCHAMI/cloud-init/internal/smdclient.(*SMDClient).ComponentInformation
      /opt/shared/cloud-init/internal/smdclient/SMDclient.go:270
    main.initCiRouter.InstanceDataHandler.func4
      /opt/shared/cloud-init/cmd/cloud-init-server/instance_data.go:56
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5.(*Mux).routeHTTP
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5.(*Mux).ServeHTTP
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:73
    github.com/go-chi/chi/v5.(*Mux).Mount.func1
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:327
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5.(*Mux).routeHTTP
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    main.main.OpenCHAMILogger.func2.1
      /root/go/pkg/mod/github.com/openchami/chi-middleware/log@v0.0.0-20240812224658-b16b83c70700/middleware.go:45
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    main.main.Timeout.func1.1
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/timeout.go:44
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5/middleware.StripSlashes.func1
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/strip.go:30
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5/middleware.Recoverer.func1
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/recoverer.go:45
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:55
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5/middleware.RealIP.func1
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/realip.go:36
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5/middleware.RequestID.func1
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/request_id.go:76
    net/http.HandlerFunc.ServeHTTP
      /opt/go/src/net/http/server.go:2220
    github.com/go-chi/chi/v5.(*Mux).ServeHTTP
      /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90
    net/http.serverHandler.ServeHTTP
      /opt/go/src/net/http/server.go:3210
    net/http.(*conn).serve
      /opt/go/src/net/http/server.go:2092
    created by net/http.(*Server).Serve in goroutine 1
      /opt/go/src/net/http/server.go:3360
```

**Comment by davidallendj** [comment]
> I'm getting a panic when I try to make a request to the endpoint with `curl -k $CLOUD_INIT_URL/instance-data`:
> 
> ```shell
> panic: runtime error: invalid memory address or nil pointer dereference
>  
>  -> github.com/OpenCHAMI/cloud-init/internal/smdclient.(*SMDClient).getSMD
>  ->   /opt/shared/cloud-init/internal/smdclient/SMDclient.go:115
> 
>     github.com/OpenCHAMI/cloud-init/internal/smdclient.(*SMDClient).ComponentInformation
>       /opt/shared/cloud-init/internal/smdclient/SMDclient.go:270
>     main.initCiRouter.InstanceDataHandler.func4
>       /opt/shared/cloud-init/cmd/cloud-init-server/instance_data.go:56
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5.(*Mux).routeHTTP
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5.(*Mux).ServeHTTP
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:73
>     github.com/go-chi/chi/v5.(*Mux).Mount.func1
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:327
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5.(*Mux).routeHTTP
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     main.main.OpenCHAMILogger.func2.1
>       /root/go/pkg/mod/github.com/openchami/chi-middleware/log@v0.0.0-20240812224658-b16b83c70700/middleware.go:45
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     main.main.Timeout.func1.1
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/timeout.go:44
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5/middleware.StripSlashes.func1
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/strip.go:30
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5/middleware.Recoverer.func1
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/recoverer.go:45
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:55
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5/middleware.RealIP.func1
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/realip.go:36
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5/middleware.RequestID.func1
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/request_id.go:76
>     net/http.HandlerFunc.ServeHTTP
>       /opt/go/src/net/http/server.go:2220
>     github.com/go-chi/chi/v5.(*Mux).ServeHTTP
>       /root/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90
>     net/http.serverHandler.ServeHTTP
>       /opt/go/src/net/http/server.go:3210
>     net/http.(*conn).serve
>       /opt/go/src/net/http/server.go:2092
>     created by net/http.(*Server).Serve in goroutine 1
>       /opt/go/src/net/http/server.go:3360
> ```

I think this should be fixed with the last commit I just pushed.

**Review by davidallendj — APPROVED** [review]
LGTM, tested, and confirmed working.

**Review by synackd — APPROVED** [review]
Tested working. Left some comments for posterity.

**Pull request merged**
