### PR TITLE
Fix issue with Update in memstore not creating new data

### PR DESCRIPTION
**Pull request by davidallendj**

### CODE REVIEW

**Comment by travisbcotton** [comment]
It now lets me add `user-data` to a group:
```
curl $CLOUD_INIT_URL/compute/user-data -X PUT -d '{"write_files": [{"content": "hello world", "path": "/etc/hello"}]}'
```
Which I can get with `curl -s $CLOUD_INIT_URL`.  
```json
{
  "compute": {
    "name": "",
    "cloud-init": {
      "userdata": {
        "write_files": [
          {
            "content": "hello world",
            "path": "/etc/hello"
          }
        ]
      },
      "metadata": null,
      "vendordata": null
    }
  }
}
```

But when I try to get a specific component's cloud-init `curl -s $CLOUD_INIT_URL/x1000c1s7b0n0` it doesn't return the correct user-data.  
```json
{
  "name": "x1000c1s7b0n0",
  "cloud-init": {
    "userdata": null,
    "metadata": {
      "groups": {}
    },
    "vendordata": null
  }
}
```
also `curl -s $CLOUD_INIT_URL/x1000c1s7b0n0/user-data` returns
```yaml
#cloud-config
{}
```

**Comment by davidallendj** [comment]
It looks like it's not storing this with the correct `IDENTIFIER` if the value for `name` is an empty string, which may be why the other two requests aren't working.

**Comment by davidallendj** [comment]
Just a quick note: I think what's probably happening is that the `curl -s $CLOUD_INIT_URL/x1000c1s7b0n0` requests may be overwriting the original data. Let me look into it.

**Comment by alexlovelltroy** [comment]
@davidallendj It's not clear to me if this is ready to be evaluated for merge or if there is more work to do.  Can you update it with a comment or tag?

**Comment by davidallendj** [comment]
I'm still working on this, but I wanted to make sure I understood what needed to change after discussing with @travisbcotton.

**Comment by davidallendj** [comment]
Closing since https://github.com/OpenCHAMI/cloud-init/pull/28 addressed the issue.

**Pull request closed without merging**
